#!/bin/sh

# some env vars that are needed to get theme switching working
export XDG_SESSION_TYPE=wayland
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_CONFIG_DIRS=/home/$(id -un)/.config/kdedefaults:/etc/xdg
export LIBGL_ALWAYS_REDIRECT=
export QT_WAYLAND_RECONNECT=1

[ -z "$HOME" ] && HOME=/tmp/

# set the hours for auto theme selection
LIGHT_HOUR=5
DARK_HOUR=18

# set your dark and light theme IDs here
DARK_THEME="org.mapple.theme.dark"
LIGHT_THEME="org.mapple.theme.light"

# previous values
_THEME=""
_GLASS="false"
_MODE="auto"

[ -f "$HOME/.theme" ] && . "$HOME/.theme"

# new values
THEME="$_THEME"
GLASS="$_GLASS"
MODE="$_MODE"

if [ -z "$1" ]; then
	if [ "$_GLASS" = "true" ]; then
		echo "current theme ${_THEME}-glass"
	else
		echo "current theme $_THEME"
	fi
	exit 0
fi

# get requested values
if [ ! -z "$1" ]; then
	THEME="$1"
	if [ ! -z "$2" ]; then
		MODE="$2"
	fi
fi

# always use smart mode for cron
if [ "$THEME" = "auto" ]; then
	MODE="smart"
fi

if [ "$MODE" = "smart" ]; then
	h=$(date +%H)

	# which theme would be autoselected
	a="dark"
	if [ $h -gt $LIGHT_HOUR ] && [ $h -lt $DARK_HOUR ]; then
		a="light"
	fi

	# this will force cron to honour existing _MODE
	if [ "$THEME" = "auto" ]; then
		if [ "$_THEME" = "$a" ] || [ "$_MODE" = "auto" ]; then
			THEME="$a"
			MODE="auto"
		else
			THEME="$_THEME"
			MODE="$_MODE"
		fi

		if [ "$_GLASS" = "true" ]; then
			THEME="${THEME}-glass"
		fi

	# determine if mode should be auto or force
	elif [ "$a" = "$THEME" ] || [ "${a}-glass" = "$THEME" ]; then
		MODE="auto"
	else
		MODE="force"
	fi
fi

# better blur values
BRIGHTNESS=1.0
CONTRAST=1.0
SATURATION=1.0
BLURSTRENGTH=8
TINT="#00000000"
GLOW="#00000000"
GLASS="false"
EDGE="false"

case "$THEME" in
	"dark-glass")
		GLASS="true"
		THEME="dark"
		BRIGHTNESS=0.9
		CONTRAST=1.1
		SATURATION=1.0
		BLURSTRENGTH=2
		GLOW="#0080D0FF"
		EDGE="true"
		;;
	"light-glass")
		GLASS="true"
		THEME="light"
		BRIGHTNESS=1.1
		CONTRAST=1.0
		SATURATION=0.9
		BLURSTRENGTH=3
		GLOW="#00f0f0f0"
		TINT="#07e0e0e0"
		;;
	"dark")
		BRIGHTNESS=0.5
		CONTRAST=1.0
		SATURATION=0.5
		BLURSTRENGTH=14
		GLOW="#0080D0FF"
		;;
	"light")
		BRIGHTNESS=1.8
		CONTRAST=0.6
		SATURATION=0.3
		BLURSTRENGTH=14
		GLOW="#80f0f0f0"
		;;
esac

# update if needed
if [ "$_THEME" != "$THEME" ] || [ "$_GLASS" != "$GLASS" ]; then
	if [ ! -z "$2" ] || [ "$MODE" = "auto" ]; then

		# update gtk theme
		dconf write /org/gnome/desktop/interface/color-scheme "'prefer-$THEME'"

		# update plasma look and feel
		if [ "$THEME" = "dark" ]; then
			lookandfeeltool -a $DARK_THEME
		else
			lookandfeeltool -a $LIGHT_THEME
		fi

		# update better blur config
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key Brightness $BRIGHTNESS
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key Contrast $CONTRAST
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key Saturation $SATURATION
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key BlurStrength $BLURSTRENGTH
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key TintColor $TINT
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key GlowColor $GLOW
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key EdgeLighting $EDGE
		qdbus6 org.kde.KWin /Effects reconfigureEffect glass

		# update konsole to use the appropriate theme (and set it to default)
		kwriteconfig6 --file konsolerc --group "Desktop Entry" --key DefaultProfile $THEME.profile
		for instance in `qdbus6 | grep konsole`; do
			for session in `qdbus6 $instance | grep '/Sessions/'`; do
				qdbus6 $instance $session org.kde.konsole.Session.setProfile $THEME
			done
		done
		# save current theme
		echo "_THEME=$THEME" > "$HOME/.theme"
		echo "_GLASS=$GLASS" >> "$HOME/.theme"
		echo "_MODE=$MODE" >> "$HOME/.theme"
		exit
	fi
fi

# if we have the mode provided, we save the updated config
if [ "$MODE" != "$_MODE" ]; then
	echo "_THEME=$THEME" > "$HOME/.theme"
	echo "_GLASS=$GLASS" >> "$HOME/.theme"
	echo "_MODE=$MODE" >> "$HOME/.theme"
fi
