#!/bin/sh

# some env vars that are needed to get theme switching working
export XDG_SESSION_TYPE=wayland
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_CONFIG_DIRS=/home/$(id -un)/.config/kdedefaults:/etc/xdg
export LIBGL_ALWAYS_REDIRECT=
export QT_WAYLAND_RECONNECT=1

# set the hours for auto theme selection
LIGHT_HOUR=5
DARK_HOUR=19

# set your dark and light theme IDs here
DARK_THEME="org.mapple.theme.dark"
LIGHT_THEME="org.mapple.theme.light"

_THEME=""
_GLASS="false"

MODE="auto"
THEME="$1"

[ -f "$HOME/.theme" ] && . "$HOME/.theme"

[ -z "$1" ] && {
	if [ "$_GLASS" = "true" ]; then
		echo "current theme ${_THEME}-glass"
	else
		echo "current theme $_THEME"
	fi
	exit 0
}

if [ "$1" = "auto" ]; then
	THEME="dark"
	h=$(date +%H)
	if [ $h -gt $LIGHT_HOUR ] && [ $h -lt $DARK_HOUR ]; then
		THEME="light"
	fi

	if [ "$_GLASS" = "true" ]; then
		THEME="${THEME}-glass"
	fi
fi

BRIGHTNESS=1.0
CONTRAST=1.0
SATURATION=1.0
BLURSTRENGTH=8
GLASS="false"

# set up better-blur values for the different theme styles
case "$THEME" in
	"dark-glass")
		GLASS="true"
		THEME="dark"
		BRIGHTNESS=0.9
		CONTRAST=1.1
		SATURATION=1.0
		BLURSTRENGTH=4
		;;
	"light-glass")
		GLASS="true"
		THEME="light"
		BRIGHTNESS=1.2
		CONTRAST=0.8
		SATURATION=1.0
		BLURSTRENGTH=4
		;;
	"dark")
		BRIGHTNESS=0.5
		CONTRAST=1.0
		SATURATION=0.5
		BLURSTRENGTH=14
		;;
	"light")
		BRIGHTNESS=1.8
		CONTRAST=0.6
		SATURATION=0.5
		BLURSTRENGTH=14
		;;
esac

if [ "$_THEME" != "$THEME" ] || [ "$_GLASS" != "$GLASS" ]; then
	if [ ! -z "$2" ] || [ "$MODE" = "auto" ]; then

		# update gtk theme
		dconf write /org/gnome/desktop/interface/color-scheme "'prefer-$THEME'"

		# update plasma look and feel
		if [ "$THEME" = "dark" ]; then
			lookandfeeltool -a $DARK_THEME
		else
			lookandfeeltool -a $LIGHT_THEME
		fi

		# update better blur config
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key Brightness $BRIGHTNESS
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key Contrast $CONTRAST
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key Saturation $SATURATION
		kwriteconfig6 --file kwinrc --group Effect-blurplus --key BlurStrength $BLURSTRENGTH
		qdbus6 org.kde.KWin /Effects reconfigureEffect forceblur

		# update konsole to use the appropriate theme (and set it to default)
		kwriteconfig6 --file konsolerc --group "Desktop Entry" --key DefaultProfile $THEME.profile
		for instance in `qdbus6 | grep konsole`; do
			for session in `qdbus6 $instance | grep '/Sessions/'`; do
				qdbus6 $instance $session org.kde.konsole.Session.setProfile $THEME
			done
		done

		# save current theme
		echo "_THEME=$THEME" > "$HOME/.theme"
		echo "_GLASS=$GLASS" >> "$HOME/.theme"
		echo "MODE=$MODE" >> "$HOME/.theme"
		exit
	fi
fi

# if we got here, we're just changing the mode
[ -z "$2" ] || {
	MODE="$2"
	echo "_THEME=$THEME" > "$HOME/.theme"
	echo "_GLASS=$GLASS" >> "$HOME/.theme"
	echo "MODE=$MODE" >> "$HOME/.theme"
}
